javascript:
(
	var modokiaddr='https://sgimera.github.io/mai_RatingAnalyzer/scripts/';
	function(j,f)
	{
		j=['mai_inner_level_milk_lock.js',
		   'calc_rating_test.js',
		   'maiRatingAnalyzer_test_body.js'];
		f=function(s,u)
		{
			if(j.length==0)
			{
				return;
			}
			u=modokiaddr+j.shift()+'?'+Date.now();
			s=document.createElement('script');
			document.body.appendChild(s);
			s.charset='UTF-8';
			s.addEventListener('load',f);
			s.src=u;
		};
		(document.readyState=='loading')?document.addEventListener('DOMContentLoaded',f):f();
	}
)();
